version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ganesha
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod_network

  redis:
    container_name: redis
    image: redis:7.2
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - prod_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/ganesha/static
      - prod_media_volume:/home/ganesha/media-files
      - H:/WORK/FREELANCE/ganesha-waterpark/generated_media/:/home/ganesha/generated_media/
      - ./:/home/ganesha
    env_file:
      - .env.prod
    image: django_app
    container_name: django_app
    depends_on:
      - postgres
      - redis
    networks:
      - prod_network
    command: /usr/bin/supervisord

volumes:
  postgres_data:
  redis_data:
  static_volume:
    external: true
  prod_media_volume:
    external: true

networks:
  prod_network:
    external: true
