version: "3.9"

services:
  test_postgres:
    container_name: test_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ganesha
    expose:
      - 5432
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - test_network

  test_redis:
    container_name: test_redis
    image: redis:7.2
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - test_redis_data:/data
    networks:
      - test_network

  api_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    expose:
      - 8000
    volumes:
      - test_static_volume:/django/static
      - H:/WORK/FREELANCE/ganesha-waterpark/generated_media_test/:/home/generated_media/
      - ./:/django
    env_file:
      - .env.test
    image: django_app
    container_name: test_django_app
    depends_on:
      - test_postgres
      - test_redis
    networks:
      - test_network
    command: /usr/bin/supervisord

volumes:
  test_postgres_data:
  test_redis_data:
  test_static_volume:
    external: true

networks:
  test_network:
    external: true
