# Generated by Django 5.0.4 on 2024-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('gate_manager', 'gate_manager'), ('costume_manager', 'costume_manager'), ('locker_manager', 'locker_manager'), ('canteen_manager', 'canteen_manager'), ('bouncer', 'bouncer')], default='bouncer', max_length=100),
        ),
    ]
