# Generated by Django 5.0.4 on 2024-05-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['locker_number']},
        ),
        migrations.AlterModelOptions(
            name='ticketprice',
            options={'ordering': ['-date']},
        ),
    ]
