# Generated by Django 5.0.4 on 2024-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakfast_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lunch_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dinner_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_price_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
