# Generated by Django 5.0.4 on 2024-05-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0002_alter_costume_options_alter_locker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
