# Generated by Django 5.0.4 on 2024-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0003_alter_locker_locker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('image_only', 'image_only'), ('image_with_text', 'image_with_text'), ('document', 'document')], default='text', max_length=50)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='whatsapp_inquiry')),
                ('sent_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sent_order'],
            },
        ),
    ]
