# Generated by Django 5.0.4 on 2024-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0004_whatsappinquirymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWhatsAppNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappinquirymessage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
