# Generated by Django 5.0.4 on 2024-06-10 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_core', '0005_extrawhatsappnumbers_whatsappinquirymessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.IntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(0, 'Locker number must be positive')]),
        ),
    ]
