# Generated by Django 5.0.4 on 2024-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adult',
            new_name='adult_male',
        ),
        migrations.AddField(
            model_name='booking',
            name='adult_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='infant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
