# Generated by Django 5.0.4 on 2024-05-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_adult_booking_adult_male_booking_adult_female_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingcanteen',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingcostume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='bookinglocker',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-updated_at']},
        ),
    ]
