# Generated by Django 5.0.4 on 2024-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_bookingcanteen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcostume',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
