# Generated by Django 5.0.4 on 2024-05-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingcostume_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcostume',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
