# Generated by Django 5.0.4 on 2024-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingcostume_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(choices=[('booking', 'booking'), ('locker', 'locker'), ('costume_return', 'costume_return')], default='booking', max_length=50),
        ),
    ]
