# Generated by Django 5.0.4 on 2024-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_returned_amount_alter_payment_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locker_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
