# Generated by Django 5.0.4 on 2024-06-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookinglocker_is_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='costume_amount',
            new_name='costume_received_amount',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='locker_amount',
            new_name='locker_received_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='costume_returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='locker_returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
