# Generated by Django 5.0.4 on 2024-06-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_costume_amount_booking_costume_received_amount_and_more'),
        ('management_core', '0006_alter_locker_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglocker',
            name='locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_core.locker'),
        ),
    ]
