# Generated by Django 5.0.4 on 2024-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_bookinglocker_locker'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_checked_in',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
